DROP TABLE `SOLARMAN_DATA` ;

CREATE TABLE `SOLARMAN_DATA` (
  `device_name` varchar(10) NOT NULL,
  `sn` varchar(16) NOT NULL,
  `parent_device` varchar(10) DEFAULT NULL,
  `device_sn` varchar(16) DEFAULT NULL,
  `updated_time` datetime NOT NULL,
  `system_time` datetime NOT NULL,
  `pcu_sw_ver` varchar(16) DEFAULT NULL,
  `pv_total_power_w_` varchar(16) DEFAULT NULL,
  `total_power_generation_w_` varchar(16) DEFAULT NULL,
  `rated_power_w_` int DEFAULT NULL,
  `model` varchar(16) DEFAULT NULL,
  `dc_voltage_pv1_v_` decimal(10,2) DEFAULT NULL,
  `dc_voltage_pv2_v_` decimal(10,2) DEFAULT NULL,
  `dc_voltage_pv3_v_` decimal(10,2) DEFAULT NULL,
  `dc_voltage_pv4_v_` decimal(10,2) DEFAULT NULL,
  `dc_current_pv1_a_` decimal(10,2) DEFAULT NULL,
  `dc_current_pv2_a_` decimal(10,2) DEFAULT NULL,
  `dc_current_pv3_a_` decimal(10,2) DEFAULT NULL,
  `dc_current_pv4_a_` decimal(10,2) DEFAULT NULL,
  `dc_power_pv1_w_` decimal(10,2) DEFAULT NULL,
  `dc_power_pv2_w_` decimal(10,2) DEFAULT NULL,
  `dc_power_pv3_w_` decimal(10,2) DEFAULT NULL,
  `dc_power_pv4_w_` decimal(10,2) DEFAULT NULL,
  `total_dc_input_power_w_` decimal(10,2) DEFAULT NULL,
  `ac_output_frequency_r_hz_` decimal(10,2) DEFAULT NULL,
  `total_ac_output_power_w_` decimal(10,2) DEFAULT NULL,
  `cumulative_production_active_kwh_` decimal(10,2) DEFAULT NULL,
  `daily_production_active_kwh_` decimal(10,2) DEFAULT NULL,
  `leak_current_ma_` int DEFAULT NULL,
  `grid_status` varchar(40) DEFAULT NULL,
  `cumulative_consumption_kwh_` decimal(10,2) DEFAULT NULL,
  `daily_consumption_kwh_` decimal(10,2) DEFAULT NULL,
  `module_temperature1_` int DEFAULT NULL,
  `single_plate_ambient_temperature_` int DEFAULT NULL,
  `radiator_temperature_1_` int DEFAULT NULL,
  `generation_time_total_min_` int DEFAULT NULL,
  `boot_countdown` int DEFAULT NULL,
  `bus_voltage_v_` decimal(10,2) DEFAULT NULL,
  `inverter_status` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`sn`,`system_time`,`updated_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

